###
# ____________________________ Authentication ____________________________

###
# login
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
    "email": "olo.a@wp.pl",
    "password": "Password1!"
}

# __________________________________ USER __________________________________
###
# Create Account
POST http://localhost:5000/users/create HTTP/1.1
Content-Type: application/json

{
    "name": "olek",
    "email": "olo1.a@wp.pl",
    "password": "Password1!",
    "confirmPassword": "Password1!"
}

###
# send reset email
POST http://localhost:5000/users/sendreset HTTP/1.1
Content-Type: application/json

{
    "email": "olo.a@wp.pl"
}

###
# send email
POST http://localhost:5000/users/email HTTP/1.1
Content-Type: application/json

{
    "email": "olo.a@wp.pl"
}

###
# get users
GET http://localhost:5000/users HTTP/1.1

###
# get me
GET http://localhost:5000/users/me HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgwN2EyMmU0Yzc5MTEzOTAzZGZmM2IiLCJuYW1lIjoib2xlayIsImlhdCI6MTYxOTAzMzA4N30.ms9aWa19vXxdQ9yKwUU2lXq7qwbUfUER6wZ3qwdyvc4

###
# confirm user
GET http://localhost:5000/users/confirmation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDdjNDY1ODMyNDdkYjBlYzRjNDIwOTQiLCJuYW1lIjoiVGVzdCBVc2VyIDAxIiwiaWF0IjoxNjE4NzU3MzM5fQ.SccUBSeekdT6frQDZZmi2WapUii3zDHATUJimYYWGyk HTTP/1.1

###
# search user by email
GET http://localhost:5000/users/search/olo.a@wp.pl HTTP/1.1

###
# new password
PUT http://localhost:5000/users/password HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgwN2EyMmU0Yzc5MTEzOTAzZGZmM2IiLCJuYW1lIjoib2xlayIsImlhdCI6MTYxOTAzMzA4N30.ms9aWa19vXxdQ9yKwUU2lXq7qwbUfUER6wZ3qwdyvc4
Content-Type: application/json

{
    "password": "Password1!",
    "confirmPassword": "Password1"
}

###
# change password
PUT http://localhost:5000/users/changepassword HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgwN2EyMmU0Yzc5MTEzOTAzZGZmM2IiLCJuYW1lIjoib2xlayIsImlhdCI6MTYxOTAzMzA4N30.ms9aWa19vXxdQ9yKwUU2lXq7qwbUfUER6wZ3qwdyvc4
Content-Type: application/json

{
    "oldPassword": "123456780",
    "password": "Password1!",
    "confirmPassword": "Password1!"
}
