# __________________________________ USER __________________________________
###
# Create Account
POST http://localhost:5000/users/create HTTP/1.1
Content-Type: application/json

{
    "name": "sampleName",
    "email": "sample@email.com",
    "password": "Password1!",
    "confirmPassword": "Password1!"
}

###
# login
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
    "email": "niblopeel@gmail.com",
    "password": "Dupa.1234"
}

#_______________________TEAMS________________

###
POST http://localhost:5000/teams HTTP/1.1
x-auth-token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgyZGJjMTEyNTc0NzBiNjBkYzFmYzgiLCJuYW1lIjoibmV3bmFtZTEiLCJpYXQiOjE2MTkyMTQxNjZ9.GsAZN4LzxwIEHT0hn6lqPMxhv-tuk0iXtFeFWO1dFGE    "name":"None""
Content-Type: application/json

{
    "name":"None"
}
