###
# ____________________________ Authentication ____________________________

###
# login
POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
    "email": "test6@user.pl",
    "password": "Password1!"
}

# __________________________________ USER __________________________________
###
# Create Account
POST http://localhost:5000/users/create HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "email": "test6@user.pl",
    "password": "Password1!",
    "confirmPassword": "Password1!"
}

###
# send reset email
POST http://localhost:5000/users/sendreset HTTP/1.1
Content-Type: application/json

{
    "email": "olo.a@wp.pl"
}

###
# send email
POST http://localhost:5000/users/email HTTP/1.1
Content-Type: application/json

{
    "email": "olo.a@wp.pl"
}

###
# get users
GET http://localhost:5000/users HTTP/1.1

###
# get user
GET http://localhost:5000/users/60832736be37ba2584bf00cb HTTP/1.1

###
# get me
GET http://localhost:5000/users/me HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgzMjczNmJlMzdiYTI1ODRiZjAwY2IiLCJuYW1lIjoidGVzdCIsImlhdCI6MTYxOTIyNjgxMn0.f_TXWKZY3j-DpCbrwj98QNfIAXzPzL0zsRLHuRYcWRA

###
# confirm user
GET http://localhost:5000/users/confirmation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDdjNDY1ODMyNDdkYjBlYzRjNDIwOTQiLCJuYW1lIjoiVGVzdCBVc2VyIDAxIiwiaWF0IjoxNjE4NzU3MzM5fQ.SccUBSeekdT6frQDZZmi2WapUii3zDHATUJimYYWGyk HTTP/1.1

###
# search user by email
GET http://localhost:5000/users/search/olo.a@wp.pl HTTP/1.1

###
# new password
PUT http://localhost:5000/users/password HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgwN2EyMmU0Yzc5MTEzOTAzZGZmM2IiLCJuYW1lIjoib2xlayIsImlhdCI6MTYxOTAzMzA4N30.ms9aWa19vXxdQ9yKwUU2lXq7qwbUfUER6wZ3qwdyvc4
Content-Type: application/json

{
    "password": "Password1!",
    "confirmPassword": "Password1!"
}

###
# change password
PUT http://localhost:5000/users/changepassword HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgwN2EyMmU0Yzc5MTEzOTAzZGZmM2IiLCJuYW1lIjoib2xlayIsImlhdCI6MTYxOTAzMzA4N30.ms9aWa19vXxdQ9yKwUU2lXq7qwbUfUER6wZ3qwdyvc4
Content-Type: application/json

{
    "oldPassword": "123456780",
    "password": "Password1!",
    "confirmPassword": "Password1!"
}

###
# change name
PUT http://localhost:5000/users/changeName HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgxZDRlN2Y5MmEzYTFkODg0ZjM1YjkiLCJuYW1lIjoiT2xlazEyMzEiLCJpYXQiOjE2MTkxNzY3Nzh9.BVKHHGBVkcq7ymKXXcApccUo_roAnwPmpltcB3O_FMg
Content-Type: application/json

{
    "name": "Olek"
}

###
# change activity
PUT http://localhost:5000/users/active HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgzMTVhMmE4ODMxZDI1ZjhmNDI3MjkiLCJuYW1lIjoib2xlayIsImlhdCI6MTYxOTIwNTcxM30.NJrvOH3ZTV56c15LT5FaTSSD7wilvs6WRrznFt0kMQY
Content-Type: application/json

{
    "isActive": true
}

###
# change email
PUT http://localhost:5000/users/changeEmail HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgxZDRlN2Y5MmEzYTFkODg0ZjM1YjkiLCJuYW1lIjoiT2xlazEyMzEiLCJpYXQiOjE2MTkxNzY3Nzh9.BVKHHGBVkcq7ymKXXcApccUo_roAnwPmpltcB3O_FMg
Content-Type: application/json

{
    "email": "olo.a@wp.pl"
}

###
# change times
PUT http://localhost:5000/users/times HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgzMjczNmJlMzdiYTI1ODRiZjAwY2IiLCJuYW1lIjoidGVzdCIsImlhdCI6MTYxOTIyNjgxMn0.f_TXWKZY3j-DpCbrwj98QNfIAXzPzL0zsRLHuRYcWRA
Content-Type: application/json

{
    "startTime": "06:00:00",
    "endTime": "14:00:00"
}

###
# delete users
DELETE  http://localhost:5000/users HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgzMjViYWQ2NmVlMzRkMmNlYWY0MmIiLCJuYW1lIjoidGVzdCIsImlhdCI6MTYxOTIwNzkyM30.e3wiJEmmjqNcBytErrt_OL05ZN8j-CKhS8atWKVQtHI
